deployment-name: sample
bosh-uuid: ac3304f5-908a-446e-8b88-5a81ed349298
stemcell-alias: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
vm-type: t2.medium
az-name: us-east-1c
network-name: infra
release-name: sample-bootapp-release
job-name: bootapp
listen-port: 8080
release-version: 1.0.0
cf-deployment-name: cf-827383743403 # ERT deployment name
app-fqdn: timetracking.sys.cfapps.io  # system domain register with GoRouter
